# Generated by Django 5.0.3 on 2024-05-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0002_alter_team_team_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Team_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SplatourneyApp.team'),
            preserve_default=False,
        ),
    ]
