# Generated by Django 5.0.3 on 2024-05-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0006_alter_bracket_tournament_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='gameEntry_Name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameentry',
            name='next_GameEntry',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
