# Generated by Django 5.0.3 on 2024-05-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SplatourneyApp', '0007_gameentry_gameentry_name_gameentry_next_gameentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameentry',
            name='next_GameEntry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
